services:
  fakestore-allure:
    build:
      context: .
      dockerfile: Dockerfile
      target: serve
    container_name: fakestore-allure
    ports:
      - "8080:8080"
    restart: unless-stopped
